### ISSUE TITLE
User.current (called class method missing)

### ISSUE THREAD

**Issue by sfcgeorge** [ruby-hyperloop/hyperloop-devise-tutorial#1]
In our app I've added the current class method but is doesn't work on the client. In fact any class method I add appears to be missing. Oddly though class methods I add to ApplicationRecord do work and are even inherited into user. Any ideas?

Restarting the server and clearing the cache has no effect.

Error:
`!! User.current() (called class method missing)`

Examples:
```ruby
class ApplicationRecord
  def self.foo
    "foo"
  end
end

class User < ApplicationRecord
  def self.bar
    "bar"
  end
end

ApplicationRecord.foo # works
User.foo # works
User.bar # error
```

**Comment by barriehadfield** [comment]
Hi Simon

Is the source in the tutorial working for you or if it only in your app?

Btw - consider reaching us in the gittet chat, there is always someone
there to help.

Barrie

**Comment by sfcgeorge** [comment]
Thank you, I will check out the Gitter.

I think this was the wrong part of Hyperloop to open the issue on. I got it working and found a bit more what was going on so opened a more specific [issue on hyper-mesh](https://github.com/ruby-hyperloop/hyper-mesh/issues/38)
